apiVersion: v1
kind: Service
metadata:
  name: postgres-product
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: postgres-product
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      
---
apiVersion: v1
kind: Service
metadata:
  name: product-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: product-api
  ports:
    - name: http
      port: 8082
      targetPort: 8082